language: csharp
solution: Stark.sln
install:
  - nuget restore Stark.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Stark.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Stark.UnitTests/bin/Release/Stark.UnitTests